### ISSUE TITLE
its free or paid?

### ISSUE THREAD

**Issue by esakarya** [odoopbx/addons#7]
Hi thank for this amazing work! 
in apps.odoo.com asterisk_plus addon price is 350€ bur here is public? What difference ? if this is public addon , can you share enterprise addon parts hr plus and helpdesk

**Comment by litnimax** [comment]
Hello.
We don't see any contradictory between LGPL-3 app sold from the app market.
We need resources to develop it further.
That's why we sell it there and also make some addons commercial like asterisk_plus_helpdesk and some others.
We have just started this new (for us) open source business model as before all our apps were not available from Github.
So if you can this app amazing why not give some power for it to thank and impove?
Here is the donation page - https://www.patreon.com/odoopbx.

**Comment by esakarya** [comment]
We will, youre welcome , great work.
